// ============================================================================
// main.bicep — Generated by infra_composer_agent
// Composed automatically from existing AVM Bicep modules based on a natural
// language infrastructure request. Do not hand-edit module wiring below;
// re-run the agent instead so the composition stays reproducible.
// ============================================================================
targetScope = 'resourceGroup'

@minLength(3)
@maxLength(20)
@description('A unique application/solution name used as base for all resource naming.')
param solutionName string = 'composedsolution'

@description('Primary Azure region for resource deployment.')
param location string = resourceGroup().location

@description('Tags to apply to all resources.')
param tags object = {}

// ============================================================================
// Modules (dependency order: prerequisites are declared before dependents)
// ============================================================================

// Auto-included dependency of a requested module: app-service-plan
module appServicePlan './modules/compute/app-service-plan.bicep' = {
  name: take('module.appServicePlan', 64)
  params: {
    solutionName: solutionName
    location: location
    tags: tags
  }
}

module appService1 './modules/compute/app-service.bicep' = {
  name: take('module.appService1', 64)
  params: {
    solutionName: solutionName
    location: location
    tags: tags
    serverFarmResourceId: appServicePlan.outputs.resourceId
    linuxFxVersion: appService1_linuxFxVersion
  }
}

module appService2 './modules/compute/app-service.bicep' = {
  name: take('module.appService2', 64)
  params: {
    solutionName: solutionName
    location: location
    tags: tags
    serverFarmResourceId: appServicePlan.outputs.resourceId
    linuxFxVersion: appService2_linuxFxVersion
  }
}

// Auto-included dependency of a requested module: container-app-environment
module containerAppEnvironment './modules/compute/container-app-environment.bicep' = {
  name: take('module.containerAppEnvironment', 64)
  params: {
    solutionName: solutionName
    location: location
    tags: tags
  }
}

module containerApp './modules/compute/container-app.bicep' = {
  name: take('module.containerApp', 64)
  params: {
    name: 'container-app-${solutionName}'
    location: location
    tags: tags
    environmentResourceId: containerAppEnvironment.outputs.resourceId
    containers: containerApp_containers
  }
}

module storageAccount './modules/data/storage-account.bicep' = {
  name: take('module.storageAccount', 64)
  params: {
    solutionName: solutionName
    location: location
    tags: tags
  }
}

module cosmosDbNosql './modules/data/cosmos-db-nosql.bicep' = {
  name: take('module.cosmosDbNosql', 64)
  params: {
    solutionName: solutionName
    location: location
    tags: tags
  }
}

module logAnalytics './modules/monitoring/log-analytics.bicep' = {
  name: take('module.logAnalytics', 64)
  params: {
    solutionName: solutionName
    location: location
    tags: tags
  }
}

module appInsights './modules/monitoring/app-insights.bicep' = {
  name: take('module.appInsights', 64)
  params: {
    solutionName: solutionName
    location: location
    tags: tags
    workspaceResourceId: logAnalytics.outputs.resourceId
  }
}

module managedIdentity './modules/identity/managed-identity.bicep' = {
  name: take('module.managedIdentity', 64)
  params: {
    solutionName: solutionName
    location: location
    tags: tags
  }
}

module keyVault './modules/security/key-vault.bicep' = {
  name: take('module.keyVault', 64)
  params: {
    solutionName: solutionName
    location: location
    tags: tags
  }
}

// ============================================================================
// Unresolved required parameters (no matching module found in the source repo)
// ============================================================================
@description('Required by a module; no local module produced a matching output.')
param appService1_linuxFxVersion string

@description('Required by a module; no local module produced a matching output.')
param appService2_linuxFxVersion string

@description('Required by a module; no local module produced a matching output.')
param containerApp_containers array


// ============================================================================
// Outputs
// ============================================================================
output APPSERVICEPLAN_RESOURCEID string = appServicePlan.outputs.resourceId
output APPSERVICEPLAN_NAME string = appServicePlan.outputs.name
output APPSERVICE1_RESOURCEID string = appService1.outputs.resourceId
output APPSERVICE1_NAME string = appService1.outputs.name
output APPSERVICE1_DEFAULTHOSTNAME string = appService1.outputs.defaultHostname
output APPSERVICE1_APPURL string = appService1.outputs.appUrl
output APPSERVICE1_IDENTITYPRINCIPALID string = appService1.outputs.identityPrincipalId
output APPSERVICE2_RESOURCEID string = appService2.outputs.resourceId
output APPSERVICE2_NAME string = appService2.outputs.name
output APPSERVICE2_DEFAULTHOSTNAME string = appService2.outputs.defaultHostname
output APPSERVICE2_APPURL string = appService2.outputs.appUrl
output APPSERVICE2_IDENTITYPRINCIPALID string = appService2.outputs.identityPrincipalId
output CONTAINERAPPENVIRONMENT_NAME string = containerAppEnvironment.outputs.name
output CONTAINERAPPENVIRONMENT_RESOURCEID string = containerAppEnvironment.outputs.resourceId
output CONTAINERAPPENVIRONMENT_DEFAULTDOMAIN string = containerAppEnvironment.outputs.defaultDomain
output CONTAINERAPPENVIRONMENT_STATICIP string = containerAppEnvironment.outputs.staticIp
output CONTAINERAPP_NAME string = containerApp.outputs.name
output CONTAINERAPP_RESOURCEID string = containerApp.outputs.resourceId
output CONTAINERAPP_FQDN string = containerApp.outputs.fqdn
output CONTAINERAPP_PRINCIPALID string = containerApp.outputs.principalId
output STORAGEACCOUNT_RESOURCEID string = storageAccount.outputs.resourceId
output STORAGEACCOUNT_NAME string = storageAccount.outputs.name
output STORAGEACCOUNT_BLOBENDPOINT string = storageAccount.outputs.blobEndpoint
output STORAGEACCOUNT_SERVICEENDPOINTS object = storageAccount.outputs.serviceEndpoints
output COSMOSDBNOSQL_RESOURCEID string = cosmosDbNosql.outputs.resourceId
output COSMOSDBNOSQL_NAME string = cosmosDbNosql.outputs.name
output COSMOSDBNOSQL_ENDPOINT string = cosmosDbNosql.outputs.endpoint
output COSMOSDBNOSQL_DATABASENAME string = cosmosDbNosql.outputs.databaseName
output COSMOSDBNOSQL_CONTAINERNAME string = cosmosDbNosql.outputs.containerName
output LOGANALYTICS_RESOURCEID string = logAnalytics.outputs.resourceId
output LOGANALYTICS_NAME string = logAnalytics.outputs.name
output LOGANALYTICS_LOCATION string = logAnalytics.outputs.location
output LOGANALYTICS_LOGANALYTICSWORKSPACEID string = logAnalytics.outputs.logAnalyticsWorkspaceId
output APPINSIGHTS_RESOURCEID string = appInsights.outputs.resourceId
output APPINSIGHTS_NAME string = appInsights.outputs.name
output APPINSIGHTS_INSTRUMENTATIONKEY string = appInsights.outputs.instrumentationKey
output APPINSIGHTS_CONNECTIONSTRING string = appInsights.outputs.connectionString
output APPINSIGHTS_APPLICATIONID string = appInsights.outputs.applicationId
output MANAGEDIDENTITY_RESOURCEID string = managedIdentity.outputs.resourceId
output MANAGEDIDENTITY_PRINCIPALID string = managedIdentity.outputs.principalId
output MANAGEDIDENTITY_CLIENTID string = managedIdentity.outputs.clientId
output MANAGEDIDENTITY_NAME string = managedIdentity.outputs.name
output KEYVAULT_NAME string = keyVault.outputs.name
output KEYVAULT_URI string = keyVault.outputs.uri
output KEYVAULT_RESOURCEID string = keyVault.outputs.resourceId
