"""
Composes the generated project: copies selected + resolved modules into a
destination folder (preserving their relative paths), then generates a
root main.bicep that declares/wires every module in dependency order,
auto-connecting parameters to upstream outputs or to shared core params
where possible, and surfacing anything it cannot resolve as a top-level
parameter instead of silently leaving a broken reference.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from module_index import ModuleInfo, fuzzy_overlap
from resolver import ResolutionResult, CORE_PARAM_NAMES, is_resource_ref_param, normalize_concept

CORE_DECLS = """@minLength(3)
@maxLength(20)
@description('A unique application/solution name used as base for all resource naming.')
param solutionName string = 'composedsolution'

@description('Primary Azure region for resource deployment.')
param location string = resourceGroup().location

@description('Tags to apply to all resources.')
param tags object = {}
"""


def _symbol_name(module: ModuleInfo, count_index: int, total_count: int) -> str:
    base = "".join(w.capitalize() for w in module.name.replace("-", "_").split("_"))
    base = base[0].lower() + base[1:]
    if total_count > 1:
        return f"{base}{count_index + 1}"
    return base


def _find_output_match(tokens: list[str], producer: ModuleInfo):
    """Find the best output on `producer` whose name looks like a resource id."""
    candidates = [o for o in producer.outputs if o.name.lower().endswith(("id", "resourceid"))]
    if not candidates:
        candidates = producer.outputs
    for o in candidates:
        if o.name.lower() in ("resourceid", "id"):
            return o
    return candidates[0] if candidates else None


def copy_modules(resolution: ResolutionResult, source_root: Path, dest_root: Path) -> dict[str, Path]:
    """Copies each resolved module's .bicep file into dest_root/modules/<rel_path>."""
    dest_modules_dir = dest_root / "modules"
    copied: dict[str, Path] = {}
    for key, module in resolution.modules.items():
        target = dest_modules_dir / module.rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(module.path, target)
        copied[key] = target
    return copied


def generate_main_bicep(resolution: ResolutionResult, requested_counts: dict[str, int]) -> str:
    lines: list[str] = []
    # Collected here whenever a required resource-ref param has no in-project
    # module to satisfy it; declared as real top-level params later so the
    # generated file never references an undefined symbol.
    fallback_params: dict[str, str] = {}  # unique_param_name -> bicep type
    lines.append("// ============================================================================")
    lines.append("// main.bicep — Generated by infra_composer_agent")
    lines.append("// Composed automatically from existing AVM Bicep modules based on a natural")
    lines.append("// language infrastructure request. Do not hand-edit module wiring below;")
    lines.append("// re-run the agent instead so the composition stays reproducible.")
    lines.append("// ============================================================================")
    lines.append("targetScope = 'resourceGroup'")
    lines.append("")
    lines.append(CORE_DECLS)

    # symbol assignment: explicit multi-count modules get numbered symbols
    symbols: dict[str, list[str]] = {}
    module_symbol: dict[str, str] = {}
    for key, module in resolution.modules.items():
        count = requested_counts.get(key, 1)
        instance_symbols = []
        for i in range(count):
            sym = _symbol_name(module, i, count)
            instance_symbols.append(sym)
        symbols[key] = instance_symbols

    lines.append("// ============================================================================")
    lines.append("// Modules (dependency order: prerequisites are declared before dependents)")
    lines.append("// ============================================================================")

    for key, module in resolution.modules.items():
        count = requested_counts.get(key, 1)
        is_dependency_only = key not in resolution.explicitly_requested
        for i in range(count):
            sym = symbols[key][i]
            rel_posix = module.rel_path.as_posix()
            lines.append("")
            if is_dependency_only:
                lines.append(f"// Auto-included dependency of a requested module: {module.name}")
            lines.append(f"module {sym} './modules/{rel_posix}' = {{")
            lines.append(f"  name: take('module.{sym}', 64)")
            lines.append("  params: {")
            for p in module.params:
                if p.name in CORE_PARAM_NAMES:
                    if p.name == "name" and p.required:
                        # "name" has no default in this module (e.g. container-app),
                        # so it must always be supplied explicitly, numbered when
                        # multiple instances of the same module are requested.
                        suffix = f"-{i + 1}" if count > 1 else ""
                        lines.append(f"    name: '{module.name}{suffix}-${{solutionName}}'")
                    elif p.name in ("solutionName", "location", "tags"):
                        lines.append(f"    {p.name}: {p.name}")
                    continue
                if is_resource_ref_param(p.name, p.type):
                    tokens = normalize_concept(p.name)
                    resolved_value = None
                    for cand_key in resolution.edges.get(key, ()):
                        cand_module = resolution.modules[cand_key]
                        overlap = fuzzy_overlap(set(tokens), cand_module.tags)
                        if overlap:
                            out = _find_output_match(tokens, cand_module)
                            if out:
                                cand_sym = symbols[cand_key][0]
                                resolved_value = f"{cand_sym}.outputs.{out.name}"
                                break
                    if resolved_value:
                        lines.append(f"    {p.name}: {resolved_value}")
                    elif p.required:
                        fallback_name = f"{sym}_{p.name}"
                        fallback_params[fallback_name] = p.type
                        lines.append(f"    {p.name}: {fallback_name} // no matching module found; declared as a top-level param")
                elif p.required:
                    # Required param with no default and not a resource reference
                    # (e.g. linuxFxVersion, containers, administrators): surface it
                    # as a top-level param instead of omitting it, which would
                    # otherwise produce an invalid/incomplete module call.
                    fallback_name = f"{sym}_{p.name}"
                    fallback_params[fallback_name] = p.type
                    lines.append(f"    {p.name}: {fallback_name}")
            lines.append("  }")
            lines.append("}")

    # Declare fallback top-level params for anything no local module could satisfy,
    # so the generated file is always self-consistent (no dangling references).
    if fallback_params:
        lines.append("")
        lines.append("// ============================================================================")
        lines.append("// Unresolved required parameters (no matching module found in the source repo)")
        lines.append("// ============================================================================")
        for pname, ptype in fallback_params.items():
            lines.append("@description('Required by a module; no local module produced a matching output.')")
            lines.append(f"param {pname} {ptype}")
            lines.append("")

    lines.append("")
    lines.append("// ============================================================================")
    lines.append("// Outputs")
    lines.append("// ============================================================================")
    for key, module in resolution.modules.items():
        for i, sym in enumerate(symbols[key]):
            for o in module.outputs:
                out_name = f"{sym.upper()}_{o.name.upper()}" if len(symbols[key]) == 1 else f"{sym.upper()}_{o.name.upper()}"
                lines.append(f"output {out_name} {o.type} = {sym}.outputs.{o.name}")

    return "\n".join(lines) + "\n"
